# Generated by Django 6.0.4 on 2026-05-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colecionavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_colecionavel', models.CharField(max_length=5)),
                ('titulo', models.CharField(max_length=255)),
                ('ano_lançamento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colecionavel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumArtista',
            fields=[
                ('pk', models.CompositePrimaryKey('id_colecionavel', 'id_artista', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'album_artista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_colecionavel', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colecao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_colecionavel', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('data_adicao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_desejos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivrosAutor',
            fields=[
                ('pk', models.CompositePrimaryKey('isbn', 'id_autor', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'livros_autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_colecionavel', models.OneToOneField(db_column='id_colecionavel', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='colecionaveis.colecionavel')),
                ('numero_catalogo', models.CharField(blank=True, max_length=50, null=True)),
                ('ean_upc', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_album', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_colecionavel', models.OneToOneField(db_column='id_colecionavel', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='colecionaveis.colecionavel')),
                ('isbn', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'db_table': 'livro',
                'managed': False,
            },
        ),
    ]
